- name: Install MySQL server on Debian family
  ansible.builtin.apt:
    name: 
      - "mysql-server={{ mysql_version }}-1ubuntu{{ ansible_distribution_version }}"
      - mysql-shell
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install MySQL packages on RedHat family
  ansible.builtin.yum:
    name:
      - "mysql-community-server-{{ mysql_version }}-1.el{{ ansible_distribution_major_version }}"
      - mysql-shell
    state: present
  when: ansible_os_family == "RedHat"

- name: Install PyMySQL for Python3 on Debian-based systems
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: true

- name: Install pip3 on RHEL-based systems
  ansible.builtin.yum:
    name: python3-pip
    state: present
  when: ansible_os_family == "RedHat"
  become: true

- name: Install PyMySQL and cryptography for Python3 on RHEL-based systems
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: /usr/bin/pip3
  when: ansible_os_family == "RedHat"
  become: true


