- name: Start MySQL service
  ansible.builtin.systemd:
    name: mysql
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Start MySQL service
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"